#spring
spring:
  application:
  name : "springLesson"
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: "jdbc:mysql://localhost:3306/lesson"
    url: "jdbc:log4jdbc:mysql://localhost:3306/lesson"
    username: "root"
    password: "1234"
#MyBatis
mybatis:
  mapper-locations: classpath:springlesson/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    jdbc.sqlonly: INFO